services:

  ghrunner:
    container_name: ghrunner
    image: snw35/ghrunner:latest
    restart: always
    environment:
      - REPOSITORY=snw35/ghrunner
      - ACCESS_TOKEN=changeme
      - RUNNER_NAME=selfhosted
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
